name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/
    - name: Test x86
      run: dotnet test --no-build --verbosity normal --framework net5.0 --runtime win-x86
      working-directory: src/Tests/
    - name: Test x64
      run: dotnet test --no-build --verbosity normal --framework net5.0 --runtime win-x64
      working-directory: src/Tests/
